### ISSUE TITLE
Zenodo link for code availability in Nature Methods paper is broken

### ISSUE THREAD

**Issue by stefanozampini** [ml-struct-bio/cryodrgn#315]
The Nature  Methods paper https://www.nature.com/articles/s41592-020-01049-4 lists https://doi.org/10.5281/zenodo.4355743 for custom code availability (I presume training and image generation scripts). The link is broken. Can you please provide the correct one?

**Comment by stefanozampini** [comment]
That zenodo link also appears in the references and contains trained weights and input data. I was hoping  the one listed in the nature website to contain information on the training process itself (like command line options for the training driver)

**Comment by zhonge** [comment]
The zenodo link probably broke since we recently migrated the repo from my personal account https://github.com/zhonge/cryodrgn to https://github.com/ml-struct-bio/cryodrgn. I can see if there's anything we can update on zenodo to fix the links.

You can find all the source data (except for the particle images, which you can download from EMPIAR) for reproducing the training here: https://github.com/zhonge/cryodrgn_empiar Let us know if you have any questions.
