### ISSUE TITLE
Automatically set --Apix in cryodrgn analyze and cryodrgn downsample

### ISSUE THREAD

**Issue by zhonge** [ml-struct-bio/cryodrgn#325]
Currently, `cryodrgn analyze` sets the output Apix to 1.0 or to a user-defined `--Apix`. We should automatically try to detect the correct pixel size (found in the `ctf.pkl`).

`cryodrgn analyze` should try to load the `ctf.pkl` (from the config.yaml), and if it for some reason can't find the Apix, keep a default of 1.0 Apix.

Also, we should fix `cryodrgn downsample` to automatically adjust the pixel size after downsampling.

**Comment by michal-g** [comment]
The problem with `cryodrgn downsample` adjusting the pixel size is that there is currently no place for an experiment to "save" the `A/px` value for a given particle stack. We can have functions like `analyze` retrieve the original value of A/px from the CTF file, but we don't want functions like `downsample` modifying the CTF file (indeed, `downsample` doesn't currently even see the CTF file as an argument).

The simplest thing to do would be to add a `--ctf` argument to `downsample` so that it can get the real A/px value instead of just defaulting to 1.0 — arguably the CTF file is an intrinsic "attribute" of a particle stack and any function that takes the former can also be expected to require the latter. `downsample` writes a new particle stack so it can save this value in the header.

Note that right now particle stacks' headers for our datasets have starting `A/px` values that don't match the corresponding CTF — we could also solve this problem by ensuring `mrcs` files in input datasets have headers that match the corresponding CTFs, so commands like `downsample` and `analyze` can just pull it from the header, and update it as necessary.

**Comment by zhonge** [comment]
I think there is a slight confusion in the pixel size in the CTF pkl. The pixel size is used together with the box size (first two columns of the ctf.pkl) to define the absolute spatial extent (in Angstroms) of the particle image, which is needed to compute the CTF for each image.

The absolute spatial extent stays constant even if we downsample the images used for training, so we can just recalculate the pixel size using the first two columns of the ctf.pkl as needed.

In downsample, we should assume the pixel size in the header of the .mrc/.mrcs file is correct and save the appropriated scaled value. For analyze, I think the simplest is to read in the ctf.pkl specified in the job's config.yaml file. If for some reason, the ctf.pkl doesn't exist (perhaps the paths were moved), then we can default to 1.0 or a user specified value.

**Comment by michal-g** [comment]
in `v3.1.0b` we have implemented handling this in `analyze` by calculating the A/px value from the CTF, taking a user value, or defaulting to 1.0, while in `downsample` we get the A/px from the header if it's there or likewise default to 1.0
