### ISSUE TITLE
box size 

### ISSUE THREAD

**Issue by dhiraj82** [ml-struct-bio/cryodrgn#353]
Hi 
    It's not really an issue but I have a box size of 324 which is not divisible by 8.  even if I am downsampling it by 2 or 3 or 4, it will not be divisible by 8. How can I get around this problem? is it ok to downsample it to 128? then how am i going to train cryodrgn without downsampling?

Thank you
Dhiraj

**Comment by ryanfeathers** [comment]
Hi Dhiraj,

You can definitely downsample by other factors! When downsampling to 128, multiply your pixel size by 324/128 and provide this value for` cryodrgn analyze --Apix`

Best,

Ryan

**Comment by michal-g** [comment]
As of `v3.3.1` we are removing the error that is thrown when `train_vae` and `train_nn` inputs are not divisible by 8, instead throwing a warning that AMP training is not optimized when not using `--no-amp` (divisibility by 8 is only an issue when using AMP).

But yes, it is ok to downsample to 128 as Ryan answered above — you may not be able to run reconstruction as fast as otherwise, but you should't encounter any other issues because of this.
