### ISSUE TITLE
ERROR to load particles with Jupyter notebook during cryoDRGN filtering after a high-res train with --ind

### ISSUE THREAD

**Issue by MunozHernandez** [ml-struct-bio/cryodrgn#363]
**Describe the bug**
ERROR when loading particles with Jupyter notebook during cryoDRGN filtering after a high-res train with --ind

**To Reproduce**
Jupyter notebook worked well in a filtering job of previous triain (00_vae) but when I use the --ind selected.pkl particles for a second round training  (01_vae) then I can not filter because an error during loading the particle in the Jupyter notebook of the cryodrgn.filtering.

**Expected behavior**
I expected the filtering index particles to be the same as load input particles. 
Error appears: 
**Additional context**
Please find below the Jupyter screenshoot with out put:
<img width="407" alt="image" src="https://github.com/ml-struct-bio/cryodrgn/assets/161059418/db236bcc-503f-474a-8312-9597879aac70">

----

**Comment by michal-g** [comment]
Thanks for pointing out this issue! We believe the bug was isolated to the notebook itself (specifically the preceding call to `dataset.ImageDataset` should not include `ind=ind_orig` as the filtering is already done manually after), so the rest of your experiment output should be fine.

We will be pushing a release including a fix to this bug; in the meantime, you can try an early version of the patched notebooks using our new development release channel:
`pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ 'cryodrgn==3.3.0a1.dev4'`

**Comment by michal-g** [comment]
FYI: we found another related issue with how the filtering was done in this notebook, and fixed it, as described at #374
